language: python
install: pip install mkdocs mkdocs-cinder
script: mkdocs build
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: qHbbUR0O0BJkPfvF3SUnXmN/mmM7Zxt5B+xhtlW8M3CdKJiFQE7zvtVW07PLsrVPm6UgaIzw8QpoRct3eV930H3CyLGViYrP67OVLavE3lzENALNxarv1m4p/W3FUqvN7lZ0VOpOUCq70nTFL3amcd39CcuSqPArhBXxWoF8i3IzZ9EP2Z8d3q3s9aBnRHCgFfMmwQ+1O03TKzAun5n4/SnbEOaxv6CcQkDWsvWdPlOL/RNs3+hCpO2MtsXap92/U642JUUANt5xeI30D00Y1qzwF2u9oaeJIf/Uk7ak+Wfe0UsiHtFHmtoTHFYml0WabY0c7wLs/IzlG81EPKdj1LeYQ5Y5JNdGvZ4D4eLUXHY1tVj48ZMzCb+vTe5l0wrjZTAyEpLVSCba52fv1/yBjwjrQjwGJg/yO25RIiBgLzllwSZLbe7T2SpIru5X5F5a3uyDAd+y5Hqa+avoqAwZazfDSSjXzWvXWQl8y5eXLDKEsAAdV2avLOjsjjMOaIpGYQCEw35ARIgq9d9JMFUNvdVfvGVZ58eKHunixmxFGsvJCv7uxLUW55hLtUerdHuyedlLnEYEjzooz9WRM7sbjHbXBCtJidPrCVEAxorCa3Z3cgwYefIYOn4Q9uSYMEKZQlvrhp+OrjB38AgIUf2h3ifwG+nfJf0Xtk8jZHr4KZM=
  on:
    branch: master
  local_dir: site
