language: python
python:
  - 2.7
  - 3.6
install:
    - pip install Sphinx
    - pip install recommonmark
    - pip install sphinx_rtd_theme
script:
    - cd docs
    - sphinx-build -b html . _build
    - make html
